'use strict';
const fs = require('fs');
const path = require('path');

const names = [
  'flame', 'clipboard-list', 'dumbbell', 'target', 'trending-up', 'lock',
  'check', 'x', 'camera', 'plus', 'droplet', 'user', 'user-round', 'zap',
  'circle-check', 'circle-x', 'utensils', 'trash-2', 'pencil', 'bell', 'minus', 'arrow-right',
];
const dir = path.join(__dirname, '../package/dist/esm/icons');

function elToStr(el) {
  const [tag, attrs] = el;
  const a = Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ');
  return `<${tag} ${a}/>`;
}

const map = {};
for (const n of names) {
  const f = path.join(dir, `${n}.mjs`);
  if (!fs.existsSync(f)) {
    console.warn('missing', n);
    continue;
  }
  const src = fs.readFileSync(f, 'utf8');
  const m = src.match(/const \w+ = (\[[\s\S]*?\]);/);
  if (!m) {
    console.warn('parse fail', n);
    continue;
  }
  const arr = eval(m[1]);
  map[n] = arr.map(elToStr).join('');
}

const out = `'use strict';

// Lucide icons (ISC) — generated by scripts/gen-icons.js
const ICON_CHILDREN = ${JSON.stringify(map, null, 2)};

function icon(name, className) {
  const cls = className || 'icon';
  const inner = ICON_CHILDREN[name];
  if (!inner) return '';
  return '<svg class="' + cls + '" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + inner + '</svg>';
}

window.icon = icon;
`;

fs.writeFileSync(path.join(__dirname, '../icons.js'), out);
console.log('icons.js:', Object.keys(map).length, 'icons');
